/// Controlled priority used for triage and target lookup.
table Priority

	column priority
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: priority

	column 'Priority Name'
		dataType: string
		summarizeBy: none
		sourceColumn: priority_name

	column 'Active Flag'
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: active_flag

	column 'Sort Order'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: sort_order

	partition Priority = m
		mode: import
		source = ```
				let
					Filtered = Table.SelectRows(ReferenceSource, each [reference_type] = "priority"),
					Selected = Table.SelectColumns(Filtered, {"reference_id", "reference_name", "active_flag", "sort_order"}),
					Renamed = Table.RenameColumns(Selected, {{"reference_id", "priority"}, {"reference_name", "priority_name"}})
				in
					Renamed
				```

	annotation PBI_ResultType = Table
